// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusOrderSystem.Models;

public partial class Bus
{
    public int BusId { get; set; }

    public string BusNumber { get; set; }

    public int ModelId { get; set; }

    public int FleetId { get; set; }

    public decimal Mileage { get; set; }

    public virtual BusFleet Fleet { get; set; }

    public virtual BusModel Model { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}