// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusOrderSystem.Models;

public partial class BusFleet
{
    public int FleetId { get; set; }

    public string FleetName { get; set; }

    public string Address { get; set; }

    public string ContactPhone { get; set; }

    public string Email { get; set; }

    public decimal HourlyRate { get; set; }

    public decimal KilometerRate { get; set; }

    public string Region { get; set; }

    public virtual ICollection<Bus> Buses { get; set; } = new List<Bus>();

    public virtual ICollection<Driver> Drivers { get; set; } = new List<Driver>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();
}