// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusOrderSystem.Models;

public partial class BusModel
{
    public int ModelId { get; set; }

    public string ModelName { get; set; }

    public string ManufacturerCompany { get; set; }

    public string ManufacturerCountry { get; set; }

    public int Capacity { get; set; }

    public int Price { get; set; }

    public virtual ICollection<Bus> Buses { get; set; } = new List<Bus>();
}