// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Configuration;

namespace BusOrderSystem.Models;

public partial class BusOrderSystemContext : DbContext
{
    private int provider { get; set; }
    public BusOrderSystemContext(DbContextOptions<BusOrderSystemContext> options, int num = 0)
        : base(options) => provider = num;

    public BusOrderSystemContext(int num = 0) => provider = num;
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        switch (provider)
        {
            case 0:
                optionsBuilder.UseSqlite(ConfigurationManager.ConnectionStrings["SQLite"].ToString());
                break;
            case 1:
                optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["SQLServer"].ToString());
                break;
        }
    }
    public virtual DbSet<Bus> Buses { get; set; }

    public virtual DbSet<BusFleet> BusFleets { get; set; }

    public virtual DbSet<BusModel> BusModels { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bus>(entity =>
        {
            entity.HasKey(e => e.BusId).HasName("PK__Buses__6A0F60B58CD41121");

            entity.HasIndex(e => e.FleetId, "IX_Buses_FleetId");

            entity.HasIndex(e => e.ModelId, "IX_Buses_ModelId");

            entity.HasIndex(e => e.BusNumber, "UQ__Buses__41D29185361DEDB5").IsUnique();

            entity.Property(e => e.BusNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Mileage).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Fleet).WithMany(p => p.Buses)
                .HasForeignKey(d => d.FleetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Buses_Fleet");

            entity.HasOne(d => d.Model).WithMany(p => p.Buses)
                .HasForeignKey(d => d.ModelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Buses_Model");
        });

        modelBuilder.Entity<BusFleet>(entity =>
        {
            entity.HasKey(e => e.FleetId).HasName("PK__BusFleet__37F02D26B03DD829");

            entity.Property(e => e.Address).HasMaxLength(200);
            entity.Property(e => e.ContactPhone).HasMaxLength(20);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FleetName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.HourlyRate).HasColumnType("decimal(10, 6)");
            entity.Property(e => e.KilometerRate).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.Region)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<BusModel>(entity =>
        {
            entity.HasKey(e => e.ModelId).HasName("PK__BusModel__E8D7A12C7E98B663");

            entity.HasIndex(e => e.ModelName, "UQ__BusModel__67DC63B5AFB8DDF9").IsUnique();

            entity.Property(e => e.ManufacturerCompany).HasMaxLength(100);
            entity.Property(e => e.ManufacturerCountry).HasMaxLength(50);
            entity.Property(e => e.ModelName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64D87C0D6E7B");

            entity.HasIndex(e => e.Phone, "UQ__Customer__5C7E359E81DA44AC").IsUnique();

            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.DriverId).HasName("PK__Drivers__F1B1CD0403878FEE");

            entity.HasIndex(e => e.FleetId, "IX_Drivers_FleetId");

            entity.Property(e => e.EmploymentDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Fleet).WithMany(p => p.Drivers)
                .HasForeignKey(d => d.FleetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Drivers_Garage");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BCF3135E616");

            entity.HasIndex(e => e.CustomerId, "IX_Orders_CustomerId");

            entity.Property(e => e.DistanceKm)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.StartTime).HasColumnType("datetime");

            entity.HasOne(d => d.Bus).WithMany(p => p.Orders)
                .HasForeignKey(d => d.BusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Bus");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Customer");

            entity.HasOne(d => d.Driver).WithMany(p => p.Orders)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Driver");
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.HasKey(e => e.ShiftId).HasName("PK__Shifts__C0A83881443D8E7B");

            entity.Property(e => e.ShiftName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Fleet).WithMany(p => p.Shifts)
                .HasForeignKey(d => d.FleetId)
                .HasConstraintName("FK_Shifts_Fleet");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
