// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusOrderSystem.Models;

public partial class Driver
{
    public int DriverId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int FleetId { get; set; }

    public DateOnly? EmploymentDate { get; set; }

    public int ExperienceYears { get; set; }

    public virtual BusFleet Fleet { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}