// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusOrderSystem.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int BusId { get; set; }

    public int CustomerId { get; set; }

    public int DriverId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public decimal? DistanceKm { get; set; }

    public virtual Bus Bus { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Driver Driver { get; set; }
}